name: Cypress Tests

on: 
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress node command
        default: node runner.js
        # npx cypress run

jobs: 
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.14.0-chrome-126.0.6478.114-1-ff-127.0.1-edge-126.0.2592.61-1
      options: --user 1001
    steps: 
      - name: Get code
        uses: actions/checkout@v4.1.7

      - name: Install dependencies 
        run: npm install

      - name: Run E2E Tests
        run: ${{ github.event.inputs.cli }}
